# Tuya Local Control services

set_device_value:
  description: Set a raw value for a specific DP on a Tuya device
  fields:
    device_id:
      description: ID of the device from configuration (device_id value)
      example: "eba100a103713e6233omm7"
      required: true
    dp:
      description: Data point (DP) ID to set
      example: 62
      required: true
    value:
      description: Value to set (can be boolean, number, or string)
      example: 3
      required: true

get_device_status:
  description: Get the full status of a Tuya device
  fields:
    device_id:
      description: ID of the device from configuration (device_id value)
      example: "eba100a103713e6233omm7"
      required: true
